<a href="https://colab.research.google.com/github/SonalGire/NumPy/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

* Creating numpy arrays:





In [ ]:
#1D array :

y = np.array([1,2,3])
print(y)
print(type(y))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#2D array:

y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D array:

y = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

* Dtype :

 Used to create a np array in any data type

In [ ]:
# dtype
y = np.array([1,2,3],dtype = float)
print(y)

[1. 2. 3.]


In [ ]:
y = np.array([0,1,2,3], dtype= bool)
y

array([False,  True,  True,  True])

* arange :

used to create a numpy array using range

In [ ]:
# arange :

y = np.arange(1,11)
y


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y = np.arange(0,10,2)
y

array([0, 2, 4, 6, 8])

* Reshape :

In [ ]:
# with reshape

y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# np.ones :

y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# np.zeros :

y = np.zeros((4,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# np.random :

y = np.random.random((3,4))
print(y)

[[0.39631    0.46703739 0.73387882 0.01212002]
 [0.4574251  0.01441546 0.99460603 0.42052068]
 [0.32103189 0.83059964 0.82339939 0.10083002]]


In [ ]:
# np.linspace :
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
#  np.identity :

y = np.identity(5, dtype=int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array Attributes :

In [ ]:
a1 = np.arange(10, dtype=int)
a2 = np.arange(10,dtype=float).reshape(2,5)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#  ndim (used for checking array dimension) :

a3.ndim

3

In [ ]:
# shape : (tells present total number of items in given array)

print(a1.shape)

print(a2.shape)

print(a3.shape)

(10,)
(2, 5)
(2, 2, 2)


In [ ]:
# size
print(a1.size)

10


In [ ]:
# itemsize : space occupied in memory

print(a3.itemsize)

8


In [ ]:
# dtype:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


* Changing Datatype :

In [ ]:
# astype : (Used for saving space in memory by changing it's datatype)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations :**

In [ ]:
# Scalar operations :

#  (Arithmetic operation):

a3 + 2

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [ ]:
# relational operations: (Comparision)

print(a3 == 2)
print(a3 >1)


[[[False False]
  [ True False]]

 [[False False]
  [False False]]]
[[[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


In [ ]:
#  Vector Operations : (when you have to work with more than 1 numpy array then use vector operations)

a4 = np.arange(10).reshape(2,5)
print(a4)
a2 + a4

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.]])

# **Numpy array functions :**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# max/min/sum/prod:

print("Max:",np.max(a1))
print("Min:",np.min(a1))
print("Sum:",np.sum(a1))
print("Product:",np.prod(a2))

Max: 9
Min: 0
Sum: 45
Product: 0.0


In [ ]:
# max/min/sum/prod:
# 0 -> column and 1 -> row

a5 = np.random.random((3,3))
print(a5)
print("-"*25)
print(np.sum(a5,axis=0))

[[0.55301988 0.17242278 0.92031512]
 [0.51678306 0.092042   0.36643026]
 [0.51545487 0.28838453 0.16776301]]
-------------------------
[1.58525782 0.55284932 1.45450839]


In [ ]:
# mean/median/std/var

print(np.mean(a5))
print(np.mean(a5,axis=1))
print(np.median(a5))
print(np.std(a5))
print(np.var(a5))

0.39917950308011957
[0.54858593 0.32508511 0.32386747]
0.366430263161197
0.24387005550602295
0.05947260397251072


In [ ]:
# trigonometric functions:
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# dot product:

a2 = np.arange(12).reshape(3,4)
print(a2)

a3 = np.arange(12,24).reshape(4,3)
print(a3)

np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents:
print(np.log(a3))
print(np.exp(a3))

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [ ]:
# round/floor/ceil

print("Round:",np.round(np.random.random((2,3))*100))
print("Floor:",np.floor(np.random.random((2,3))*100))
print("Ceil:",np.ceil(np.random.random((2,3))*100))

Round: [[70.  9. 97.]
 [75. 76. 87.]]
Floor: [[31. 57. 74.]
 [80. 50. 50.]]
Ceil: [[34. 34.  3.]
 [55.  9. 45.]]


# **Indexing and slicing:**

In [ ]:
a1 = np.arange(10, dtype=int)
a2 = np.arange(12,dtype=int).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[0]
a1[-1]

np.int64(9)

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# find 7 at which index?

# num_array[row,column]
print(a2[2,1])

print(a2[2:])

7
[[ 6  7  8]
 [ 9 10 11]]


# **Iterating :**

In [ ]:
# 1D array
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# 2D array:
for i in a2:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [ ]:
# 3D array:
for i in a3:
  print(i)

# for iterating each item from any 2D to nD array:

for i in np.nditer(a3):
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
0
1
2
3
4
5
6
7


# **Reshaping:**

In [ ]:
# reshape -> Done
# Transpose
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
# ravel : used for converting any dimension array in 1D array
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])